// Code generated by cmd/generate_models_file.go, DO NOT EDIT.

package openai

//go:generate go run -tags=generate_models_file cmd/generate_models_file.go -file constants.gen.go

const (
	ModelBabbage002             = "babbage-002"
	ModelDALLE2                 = "dall-e-2"
	ModelDALLE3                 = "dall-e-3"
	ModelDavinci002             = "davinci-002"
	ModelGPT35Turbo             = "gpt-3.5-turbo"
	ModelGPT35Turbo0125         = "gpt-3.5-turbo-0125"
	ModelGPT35Turbo0301         = "gpt-3.5-turbo-0301"
	ModelGPT35Turbo0613         = "gpt-3.5-turbo-0613"
	ModelGPT35Turbo1106         = "gpt-3.5-turbo-1106"
	ModelGPT35Turbo16K          = "gpt-3.5-turbo-16k"
	ModelGPT35Turbo16K0613      = "gpt-3.5-turbo-16k-0613"
	ModelGPT35TurboInstruct     = "gpt-3.5-turbo-instruct"
	ModelGPT35TurboInstruct0914 = "gpt-3.5-turbo-instruct-0914"
	ModelGPT4                   = "gpt-4"
	ModelGPT40125Preview        = "gpt-4-0125-preview"
	ModelGPT40613               = "gpt-4-0613"
	ModelGPT41106Preview        = "gpt-4-1106-preview"
	ModelGPT41106VisionPreview  = "gpt-4-1106-vision-preview"
	ModelGPT4Turbo              = "gpt-4-turbo"
	ModelGPT4Turbo20240409      = "gpt-4-turbo-2024-04-09"
	ModelGPT4TurboPreview       = "gpt-4-turbo-preview"
	ModelGPT4VisionPreview      = "gpt-4-vision-preview"
	ModelTextEmbedding3Large    = "text-embedding-3-large"
	ModelTextEmbedding3Small    = "text-embedding-3-small"
	ModelTextEmbeddingAda002    = "text-embedding-ada-002"
	ModelTTS1                   = "tts-1"
	ModelTTS11106               = "tts-1-1106"
	ModelTTS1Hd                 = "tts-1-hd"
	ModelTTS1Hd1106             = "tts-1-hd-1106"
	ModelWhisper1               = "whisper-1"
)
